apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-env-config

  labels:
    app: qubernetes
    name: quorum-env-config
data:
  QUORUM_NODE1_SERVICE_HOST: 10.100.157.27
  QUORUM_NODE2_SERVICE_HOST: 10.100.96.43
  QUORUM_NODE3_SERVICE_HOST: 10.100.75.184
  QUORUM_NODE4_SERVICE_HOST: 10.100.87.128

---
# kubectl create configmap game-config --from-file=configure-pod-container/dd1/key
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-permissioned-config

  labels:
    app: qubernetes
    name: quorum-permissioned-config
data:
  permissioned-nodes.json: |

    [
      "enode://60380ae7841943b431cc59a4da1b917ef43a13b9548436c5df35c39e28ee88a08514c52d4a1c8b565754c2a9207e004809ac45076171dcbfdcdf9cad0ddc4d11@%QUORUM-NODE1_SERVICE_HOST%:30303?discport=0",
      "enode://f633e5bad740e7b33e82452b8e88b8503dcd65611e98e3dad7e2fd62e34066f39d80228a117026e268b8a4c6afc9fff1084485de9430228b94f3820627c0fefd@%QUORUM-NODE2_SERVICE_HOST%:30303?discport=0",
      "enode://d07a35d6a45822f0d0df9b04141658946d850ae3ce34f21df7e142b3baf1c553a500162d7543bd146dbc7badd6e838f2bb3eaac05d8d55fc283cce598d5a6fb4@%QUORUM-NODE3_SERVICE_HOST%:30303?discport=0",
      "enode://d57d56da6bbe5bdd8293de2eaa4592d12a9995b7b44f0525e615bdbb3d60dc6627d13e6221b3e54c20704a00c0aa71fe62b25f23400eb4d800c0da3fdcdbc265@%QUORUM-NODE4_SERVICE_HOST%:30303?discport=0"
    ]

  permissioned-update.sh: |
    #!/bin/bash
    PERM_NODE_TMPL=$(cat $QHOME/permission-nodes/permissioned-nodes.json.tmpl);
    PERM_NODE_JSON=$(echo $PERM_NODE_TMPL |  sed "s/%QUORUM-NODE1_SERVICE_HOST%/$QUORUM_NODE1_SERVICE_HOST/g" |  sed "s/%QUORUM-NODE2_SERVICE_HOST%/$QUORUM_NODE2_SERVICE_HOST/g" |  sed "s/%QUORUM-NODE3_SERVICE_HOST%/$QUORUM_NODE3_SERVICE_HOST/g" |  sed "s/%QUORUM-NODE4_SERVICE_HOST%/$QUORUM_NODE4_SERVICE_HOST/g" );
    echo $PERM_NODE_JSON >  $QUORUM_DATA_DIR/permissioned-nodes.json;
    cp $QUORUM_DATA_DIR/permissioned-nodes.json $QUORUM_DATA_DIR/static-nodes.json;



---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-management

  labels:
    app: qubernetes
    name: node-management
data:
  ibft_propose.sh: |-
    #/bin/ash

    if [ $# -lt 1 ]; then
      echo " An address to vote in, or out, must be provided: "
      echo " ./propose_ibft.sh HEX_ADDRESS (true|false)"
    fi

    ADDRESS=$1
    VOTE_BOOL=true

    if [ $# -eq 2 ]; then
     VOTE_BOOL=$2
    fi
    RES=$(geth --exec "istanbul.propose(\"$1\", $VOTE_BOOL)" attach ipc:$QUORUM_HOME/dd/geth.ipc)
    echo $RES
  ibft_propose_all.sh: |-
    #!/bin/ash
    set -xe

    for Addr in $( awk '/validators/,0' $QHOME/istanbul-validator-config.toml/istanbul-validator-config.toml | grep "0x" | sed 's/,//g; s/"//g' ); do
      echo $Addr
      $QHOME/node-management/ibft_propose.sh $Addr true
    done
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: istanbul-validator-config.toml

  labels:
    app: qubernetes
    name: istanbul-validator-config
data:
  istanbul-validator-config.toml: |-
    vanity = "0x00"
    validators = [
    "0x02F3c9ACa6EEa7F4D46d6523Bd95946320Bb40E2",
    "0x01A460Ec9FfED9D43B77A539b7d98F96f042F0Db",
    "0x1906B9bba9C6056e8C57e63Cd8C72BA636E697d6",
    "0x5245c22b46677DC101d77DF4Cb23FD97c6632F27",
    ]


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: geth-helpers

  labels:
    app: qubernetes
    name: geth-helpers
data:
  geth-attach.sh: |-
    #!/bin/sh

    # helper for connecting to geth from
    # outside the container
    # kubectl exec -it $POD -c quorum -- /geth-helpers/geth-attach.sh
    echo "connecting to geth $QHOME"
    geth attach $QHOME/dd/geth.ipc
  geth-exec.sh: |-
    #!/bin/sh

    # helper for connecting to geth from
    # outside the container
    # kubectl exec -it $POD -c quorum -- /geth-helpers/geth-exec.sh "admin.peers.length"

    GETH_CMD="eth.blockNumber"
    if [ "$#" -gt 0 ]; then
      GETH_CMD=$1
    fi
    # see: https://github.com/ethereum/go-ethereum/pull/17281
    # https://github.com/ethereum/go-ethereum/issues/16905
    # to avoid warning being returned
    # "WARN [02-20|00:21:04.382] Sanitizing cache to Go's GC limits  provided=1024 updated=663"
    geth --exec $GETH_CMD  --cache=16   attach $QHOME/dd/geth.ipc
