apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/quorum-examples-net: "true"
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: MONGO_CLIENT_URI
              value: mongodb://mongodb:27017
            - name: MONGO_DB_NAME
              value: epirus
            - name: NODE_ENDPOINT
              valueFrom:
               configMapKeyRef:
                 name: explorer-configs
                 # Specify the key associated with the value
                 key: QUORUM_NODE_URL
            - name: REINDEX_ENDPOINT
              value: http://ingestion/reindex/
          image: web3labs/epirus-free-api:latest
          imagePullPolicy: ""
          name: api
          resources: {}
          ports:
            - containerPort: 8090
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
