


# kubectl create configmap game-config --from-file=configure-pod-container/dd1/key
# the key used for private transactions
# quorum transaction manager keys
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node1-tm-key-config
  
  labels:
    app: qubernetes
    name: quorum-node1-tm-key-config
data:
  tm.key: |-
    {"data":{"bytes":"wWgkMgCOvL7fzFzCwnlbpaS4YVteVzjoCsiwtW/lfEM="},"type":"unlocked"}
  tm.pub: |-
    NkRFZsp9FA7QFIWZTSWflJ9+ieMkwJ7aamf+ftnv0BM=
---
# kubectl create configmap game-config --from-file=configure-pod-container/dd1/key
# nodekey (enode) (geth/ethereum)
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node1-nodekey-config
  
  labels:
    app: qubernetes
    name: quorum-node1-nodekey-config
data:
  nodekey: |
    dec6e3008a19b3908c8beb6f45bd65b4d853bb13e8124f8c919fdc57866a78c7
---
# kubectl create configmap game-config --from-file=configure-pod-container/dd1/key
# nodekey (enode) (geth/ethereum)
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node1-enode-config
  
  labels:
    app: qubernetes
    name: quorum-node1-enode-config
data:
  enode: |
    60380ae7841943b431cc59a4da1b917ef43a13b9548436c5df35c39e28ee88a08514c52d4a1c8b565754c2a9207e004809ac45076171dcbfdcdf9cad0ddc4d11

# ethereum / geth account keys (keystore)
---
# kubectl create configmap game-config --from-file=configure-pod-container/dd1/key
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node1-account-key-config
  
  labels:
    app: qubernetes
    name: quorum-node1-account-key-config
data:
  key: |-


    {"address":"66d66805e29eab59901f8b7c4cae0e38af31cb0e","crypto":{"cipher":"aes-128-ctr","ciphertext":"77bc29750cde8210ca7d94af891791574548a6f2643e4d2e0383b38ed1ce67ce","cipherparams":{"iv":"4ce907cbf67bed7e0e35ae563e168dd0"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"d7a2b59b3e9c0c4fa159b99d1d38469172d0f41203828b52b17fb898ff65a02e"},"mac":"fe97cf1df38df1d1ee488f56f124d5abf833553d0306a6d1f27fcfee2e14fd5c"},"id":"9328092d-d3d0-4b3c-ae79-0045126e2055","version":3}
# end node

# kubectl create configmap game-config --from-file=configure-pod-container/dd1/key
# the key used for private transactions
# quorum transaction manager keys
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node2-tm-key-config
  
  labels:
    app: qubernetes
    name: quorum-node2-tm-key-config
data:
  tm.key: |-
    {"data":{"bytes":"7xpWKXr6/jJ782sVC/CVsoELH3OCbBk7xhTNhldWjGY="},"type":"unlocked"}
  tm.pub: |-
    jyPmTXxHu36mBwHr9MHksxMn/PcUgQD4vxbzK1PPnyo=
---
# kubectl create configmap game-config --from-file=configure-pod-container/dd1/key
# nodekey (enode) (geth/ethereum)
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node2-nodekey-config
  
  labels:
    app: qubernetes
    name: quorum-node2-nodekey-config
data:
  nodekey: |
    14bacca7f787d5aa8c825c102bf71cca3df6a2154efd41689cd536e8dfc240e6
---
# kubectl create configmap game-config --from-file=configure-pod-container/dd1/key
# nodekey (enode) (geth/ethereum)
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node2-enode-config
  
  labels:
    app: qubernetes
    name: quorum-node2-enode-config
data:
  enode: |
    f633e5bad740e7b33e82452b8e88b8503dcd65611e98e3dad7e2fd62e34066f39d80228a117026e268b8a4c6afc9fff1084485de9430228b94f3820627c0fefd

# ethereum / geth account keys (keystore)
---
# kubectl create configmap game-config --from-file=configure-pod-container/dd1/key
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node2-account-key-config
  
  labels:
    app: qubernetes
    name: quorum-node2-account-key-config
data:
  key: |-


    {"address":"25211bfc3e3d5cc76f79841a0d43dd180c0ee5a7","crypto":{"cipher":"aes-128-ctr","ciphertext":"257be80c36cb9a4de82750cd1bdab9c15d739cc127aafbee65ac1587c29e9b24","cipherparams":{"iv":"800949e3c45eda212902b5931c488505"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"4222ad6d95313524dd0c7c3c547566d08b90e37fcb2f1fb3780d9bfb51e25210"},"mac":"2b39fec4f6071bd96051304ea2b3a24822c1670f20e0c954d1aa8cd3170bc837"},"id":"e610ce40-e79c-483d-a8b5-84dc8728d605","version":3}
# end node